[project]
name = "stacks-quest"
description = "Daily on-chain puzzle game on Stacks"
authors = ["wkalidev <wkalidev@base2stacks.io>"]
telemetry = false
cache_dir = "./.cache"
requirements = [
  { contract_id = "SP1V72500C63KN9E348QDK9X879MASSTN0J3KBQ5N.b2s-token-v4" }
]

[repl]
costs_version = 2
parser_version = 2

[contracts.stacks-quest]
path = "contracts/stacks-quest.clar"
clarity_version = 2
epoch = 2.5
